CREATE TABLE "ServerNode" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "name" TEXT NOT NULL,
  "baseUrl" TEXT NOT NULL,
  "publicIp" TEXT NOT NULL DEFAULT '',
  "apiToken" TEXT NOT NULL,
  "isLocal" BOOLEAN NOT NULL DEFAULT false,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" DATETIME NOT NULL
);

ALTER TABLE "GameServer" ADD COLUMN "nodeId" TEXT;
