ALTER TABLE "GameServer" ADD COLUMN "fsGame" TEXT NOT NULL DEFAULT '';
ALTER TABLE "GameServer" ADD COLUMN "punkbuster" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "GameServer" ADD COLUMN "configFile" TEXT NOT NULL DEFAULT '';
ALTER TABLE "GameServer" ADD COLUMN "rconPassword" TEXT NOT NULL DEFAULT '';
ALTER TABLE "GameServer" ADD COLUMN "extraParameters" TEXT NOT NULL DEFAULT '';
